Applications/website_snake/controller/__init__.py
import logging
from logging.handlers import RotatingFileHandler
from flask import Flask
from config import config_dict


# 设置日志(目的是将flask默认的日志和自定义的日志保存到文件中)
def setup_log(log_level):
    # 设置日志的记录等级
    logging.basicConfig(level=log_level)  # 根据配置类型设置日志等级

    # 创建日志记录器，指明日志保存的路径、每个日志文件的最大大小、保存的日志文件个数上限
    file_log_handler = RotatingFileHandler("logs/log", maxBytes=1024 * 1024 * 100, backupCount=10)
    # 创建日志记录的格式 日志等级 输入日志信息的文件名 行数 日志信息
    formatter = logging.Formatter('%(levelname)s %(pathname)s:%(lineno)d %(message)s')
    # 为刚创建的日志记录器设置日志记录格式
    file_log_handler.setFormatter(formatter)
    # 为全局的日志工具对象（flask app使用的）添加日志记录器
    logging.getLogger().addHandler(file_log_handler)


# 工厂函数: 由外界提供物料, 在函数内部封装对象的创建过程
def create_app(config_type):  # 封装web应用的创建过程
    # 根据类型取出对应的配置子类
    config_class = config_dict[config_type]
    app = Flask(__name__)
    app.config.from_object(config_class)

    # 注册蓝图对象  如果内容只在文件中使用一次, 最好在使用前才导入, 可以有效避免导入错误
    from controller.modules.home import home_blu
    app.register_blueprint(home_blu)
    #from controller.modules.user import user_blu
    #app.register_blueprint(user_blu)

    # 设置日志
    setup_log(config_class.LOG_LEVEL)

    return app

Applications/website_snake/controller/modules/home/__init__.py
from flask import Blueprint

# 创建蓝图对象
home_blu = Blueprint("home", __name__)

# 让视图函数和主程序建立关联
from controller.modules.home.views import *

Applications/website_snake/controller/modules/home/views.py
from flask import session, render_template, redirect, url_for, Response
from controller.modules.home import home_blu
from controller.utils.camera import VideoCamera

video_camera = None
global_frame = None


# 主页
@home_blu.route('/')
def index():
    # 模板渲染
    #username = session.get("username")
    #if not username:
    #    return redirect(url_for("user.login"))
    return render_template("index.html")


# 获取视频流
def video_stream():
    global video_camera
    global global_frame

    if video_camera is None:
        video_camera = VideoCamera()

    while True:
        frame = video_camera.get_frame()

        if frame is not None:
            global_frame = frame
            yield (b'--frame\r\n'
                   b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n\r\n')
        else:
            yield (b'--frame\r\n'
                   b'Content-Type: image/jpeg\r\n\r\n' + global_frame + b'\r\n\r\n')


# 视频流
@home_blu.route('/video_viewer')
def video_viewer():
    # 模板渲染
    #username = session.get("username")
    #if not username:
    #    return redirect(url_for("user.login"))
    return Response(video_stream(),
                    mimetype='multipart/x-mixed-replace; boundary=frame')

Applications/website_snake/controller/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>监控系统</title>
    <style>
        body {
            background-color: #484856;
        }

    </style>
</head>
<body>
<h1 align="center" style="color: whitesmoke;">手势识别系统</h1>
<div class="top">
    <div class="recorder" id="recorder" align="center">
        <button id="record" class="btn">开始游戏</button>
        

        <a id="download"></a>
        <script type="text/javascript" src="{{ url_for('static', filename='recorder.js') }}"></script>
    </div>
</div>
<img id="video" src="{{ url_for('home.video_viewer') }}">
</body>
</html>